### PR TITLE
Update UG, DG, PPP and fix issues

### LINKED ISSUE #205: Calorie count can take unlimited number of 0 after decimal
unlimited_decimals

### LINKED ISSUE #206: Zeroes before the actual calorie count are not ignored in the display
zeroes_before

### LINKED ISSUE #208: UG not clear on what goes into statistics (minor)
Hi was pretty confused reading the UG but maybe you can add a line before the stats instruction to say exactly what the stats will derive its data from e.g when you complete a scheduled regime.

### LINKED ISSUE #210: Numbers allowed in exercise name
Instructions suggest that only alphabets and spaces should be allowed.

numbers_in_names

### LINKED ISSUE #213: UG delete command example typo
should it be t/regime instead?
image

### LINKED ISSUE #214: Chart - label for 0% exercise still visible
Not sure if its intended for the label to still be there even though its 0%
image

### LINKED ISSUE #220: Exercise name can be edited to have numbers in them
This is contradictory with the error message that says only alphabets and spaces are allowed

### PR DESCRIPTION
**Pull request by jietung**
- Changed calories to Integer
- Fix #205 unlimited 0 after decimal
- Fix #208 UG for stats not clear
- Fix #210 numbers allow in exercise name
- Fix #213 UG delete regime command typo
- Fix #220 Edit name allow numbers 
- Fix #214 Pie chart 0% label visible

### CODE REVIEW

File: src/main/java/seedu/exercise/logic/commands/DeleteRegimeCommand.java [hunk 1]
```diff
@@ -25,13 +25,14 @@
...
 
+//@@author jietung
 /**
  * Deletes a regime identified using it's name or deletes exercises in regime.
  */
 public class DeleteRegimeCommand extends DeleteCommand implements PayloadCarrierCommand {
 
-    public static final String MESSAGE_USAGE_REGIME = "Parameters: REGIME NAME, INDEX (must be a positive integer)\n"
-            + "\t\tExample: "
+    public static final String MESSAGE_USAGE_REGIME = "Parameters: REGIME NAME, INDEX (must be a positive integer)"
```
Comment (t-cheepeng) [inline src/main/java/seedu/exercise/logic/commands/DeleteRegimeCommand.java]: most of us have placed the `PREFIX_NAME` in front of the message usage. Please keep it standard

Comment (jietung) [reply src/main/java/seedu/exercise/logic/commands/DeleteRegimeCommand.java]: ok
